AWSTemplateFormatVersion: "2010-09-09"
Description: "OpenVPN/stunnel on EC2"

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: "conma"
    Description: "SSH key pair (ed25519 recommended)"
  SSHPort:
    Type: Number
    Default: 22
    Description: "Custom SSH port"

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow custom SSH port"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref SSHPort
          ToPort: !Ref SSHPort
          CidrIp: 0.0.0.0/0

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.nano
      ImageId: ami-0e63a5a9c1c7e5563
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref SecurityGroup
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: 8
            VolumeType: gp3
      UserData:
        Fn::Base64: !Sub |
          #!/usr/bin/env bash
          set -e
          # Update system
          # apt update -y
          # apt upgrade -y
          # Load scripts from GitHub
          # Run install.sh


Outputs:
  InstanceId:
    Description: "EC2 Instance ID"
    Value: !Ref EC2Instance

  PublicIP:
    Description: "Public IP of the instance"
    Value: !GetAtt EC2Instance.PublicIp

  SSHCommand:
    Description: "SSH command to connect"
    Value: !Sub "ssh -i <your-key.pem> -p ${SSHPort} admin@${EC2Instance.PublicIp}"